### ISSUE TITLE
Some objects lose their collision, but remain visible.

### ISSUE THREAD

**Issue by vitalii2011** [Royal-Modding/FS19_MapObjectsHider#16]
https://drive.google.com/file/d/1jL_cVU-kahsLrYyb8JTmQsTQRJj5kEcR/view?usp=sharing 
Sosnovka map. 
```
    <hiddenObjects>
        <object name="LOD1" index="8|11|10|50|1" hash="f63de28772a5555e5d500a3a7cd341cd" date="14/04/2021" time="21:09:34" player="Mavra">
            <collision name="LOD1" index="8|11|10|50|1" rigidBodyType="Static"/>
        </object>
    </hiddenObjects>
```

**Comment by TyKonKet** [comment]
We will investigate it.

**Comment by vitalii2011** [comment]
Map of hidden objects – very convenient, but is it possible to highlight them as in GlobalCompany? Large buildings are now visible, but such "thin" objects as pillars are not always visible.

**Comment by TyKonKet** [comment]
We have to work to improve it.
