### ISSUE TITLE
Request for FS22

### ISSUE THREAD

**Issue by audhen** [Royal-Modding/FS19_MapObjectsHider#20]
Hi there!

I really do love your objects hider mod, because every map has some obstacles...
So by using your mod, every map will be playable :)

Do you have a roadmap for FS22?

**Comment by pvm** [comment]
Please! I can't survive without this mod :(

**Comment by darincraven** [comment]
I also hope this Mod will be ported to FS22.  It is one of the more useful mods for sure!

**Comment by Achimobil** [comment]
Can anyone from the Royal Modding Team contact me for convert permissions?
https://discord.com/invite/Va7JNnEkcW

**Comment by TyKonKet** [comment]
Do it, for us it's ok!

**Comment by TyKonKet** [comment]
Do it, for us it's ok!

**Comment by Achimobil** [comment]
When anyone find this question here. ModHub will take a while, they have new rules and so.
But here I have published it and anybody is welcome to use.
Last version has no reported errors currently.
https://forbidden-mods.de/filebase/file/39917-map-objects-hider/
