### ISSUE TITLE
The hide option does not appear

### ISSUE THREAD

**Issue by KITT3000** [Royal-Modding/FS19_MapObjectsHider#3]
Hello, I waited for such a mod for quite a long time, unfortunately it turned out that there is a conflict in my case and I can't hide objects. The problem is more precisely when I have this mod active on the Hof Bergmann map (v1.0.0.7) and I have the Seasons mod (v1.3.2.0) active. When I have active seasons on this map, the hide option does not appear at all (I can turn on the settings menu), I checked a lot of objects and I couldn't hide on any of them. However, if I deactivate seasons or change the map and I have active seasons, the mod works fine.

**Comment by TyKonKet** [comment]
Thank you so much to help us improve our mods.
We will investigate it soon.

**Comment by TyKonKet** [comment]
Hi @KITT3000 I should have fixed it, keep in mind that to make it work I may have broken something with animals if you are also using seasons.
We will soon release an RC version her on GitHUb so that you can give it a try.

**Comment by KITT3000** [comment]
Now it is working, thx.
