### ISSUE TITLE
Bäume ausblenden

### ISSUE THREAD

**Issue by xerion8300** [Royal-Modding/FS19_MapObjectsHider#4]
Hallo wird es auch mal eine Option geben das man Bäume ausblenden kann.

**Comment by TyKonKet** [comment]
English please, I don't understand German :(

**Comment by xerion8300** [comment]
Hello, will there be an option to hide trees?

**Comment by TyKonKet** [comment]
Oh yes, that's part of our plans.

**Comment by xerion8300** [comment]
That is very nice

**Comment by TyKonKet** [comment]
Hi @xerion8300 
The feature have been added, you can download the preview version [here](https://github.com/Royal-Modding/FS19_MapObjectsHider/releases/tag/1.2.0.0-RC1).

**Comment by xerion8300** [comment]
Hello, the mod will also come for FS22.
