### ISSUE TITLE
The gates cannot be hidden

### ISSUE THREAD

**Issue by KITT3000** [Royal-Modding/FS19_MapObjectsHider#9]
I was removing the fence on the map and unfortunately it does not detect the gate (which can be opened by the player), is it possible to add such an option in this mod?

**Comment by TyKonKet** [comment]
That's very hard to implement because unluckily the module of base game that takes care of the map animated objects is not documented at all.

**Comment by KITT3000** [comment]
As for incomplete documentation on GDN, I could help with it, but it's somewhere on a private message.

**Comment by TyKonKet** [comment]
Is it discord ok?
TyKonKet#1073

**Comment by KITT3000** [comment]
I noticed that when you try to hide the gate, the trigger disappears, so you can't control it again.

**Comment by TyKonKet** [comment]
I'm working on it!

**Comment by TyKonKet** [comment]
This feature have been added with https://github.com/Royal-Modding/FS19_MapObjectsHider/commit/c0ca67d2f523418ed0b184e1fed0acf45278a111
We are still working on other features, as soon as it will be all ready we will publish a new RC version.
